name: Android, Wear and JVM CI

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: android-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: 'true'

    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.5.0

    - name: Wear Unit Tests
      run: ./gradlew :androidApp:testDebugUnitTest :wearApp:testDebugUnitTest

    - name: Build
      run: ./gradlew :androidApp:assembleDebug :wearApp:assembleDebug

  build-jvm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0

      - name: Build
        run: ./gradlew :shared:runJvmMain
