name: Android Instrumentation

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: android-instrumentation-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - run: ./gradlew :wearApp:roundApi28Check


