name: Backend Test

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: backend-test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-backend:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3.5.0

    - uses: hashicorp/setup-terraform@v3

    - name: Build
      run: ./gradlew :backend:service-graphql:build :backend:service-import:build
