name: iOS CI

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: ios-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build iOS app
        run: xcodebuild -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 8' build

      - name: Run iOS unit tests
        run: xcodebuild test -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 8' build -test-timeouts-enabled YES