name: Publish Android & KMMBridge

on:
  push:
    branches:
      - 'main'
    paths:
      - 'androidApp/**'
      - 'shared/**'
      - ".github/workflows/**"

env:
  MAVEN_USERNAME: ${{ secrets.REPSY_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.REPSY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-home-cache-cleanup: true

      - name: Build
        run: |
          ./gradlew :androidApp:assembleGithubRelease kmmBridgePublish

      - uses: actions/upload-artifact@v3
        with:
          name: androidApp-githubRelease.apk
          path: androidApp/build/outputs/apk/release/androidApp-githubRelease.apk
