name: Publish Android

on:
  push:
    branches:
      - 'main'
    paths:
      - 'androidApp/**'
      - 'shared/**'
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1
        with:
          gradle-home-cache-cleanup: true

      - name: Build
        run: |
          ./gradlew :androidApp:assembleGithubRelease

      - uses: actions/upload-artifact@v4
        with:
          name: androidApp-githubRelease.apk
          path: androidApp/build/outputs/apk/release/androidApp-githubRelease.apk
