name: Update GraphQL schema
on:
  schedule:
    - cron: "0 0 * * *"
#  pull_request

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: apollographql/update-graphql-schema@4b4517cad731e2564488f203de81937dcc4ef92e #main
        with:
          key: ${{ secrets.APOLLO_KEY }}
          graph: "Confetti"
          schema: "shared/src/commonMain/graphql/schema.graphqls"
